# Publish values in json message and filter NaN values (they will not get published)
# Used `uptime` platform to execute the publish in a fixed interval.

- platform: uptime
  id: publish_illuminance_indoor_json
  update_interval: ${publish_temperature_interval}
  on_value:
    if:
      condition:
        lambda: 'return !isnan(id(indoor_illuminance).state);'
      then:
        - mqtt.publish_json:
            topic: ${base_topic}/indoor_illuminance
            retain: True
            payload: |-
              root["illuminance"] = round(id(indoor_illuminance).state * 100) / 100;
