# Publish values in json message and filter NaN values (they will not get published)
# Used `uptime` platform to execute the publish in a fixed interval.

- platform: uptime
  id: publish_temperature_indoor_json
  update_interval: ${publish_temperature_interval}
  on_value:
    if:
      condition:
        lambda: 'return !isnan(id(indoor_temperature).state);'
      then:
        - mqtt.publish_json:
            topic: ${base_topic}/indoor
            payload: |-
              root["temperature"] = id(indoor_temperature).state;
