ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: .rnd7.de
  
  manual_ip:
    #static_ip: 192.168.3.218
    static_ip: 192.168.3.213
    gateway: 192.168.3.3
    subnet: 255.255.255.0
    dns1: 192.168.3.3
