ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  domain: .rnd7.de

 # Removed (Switch to DHCP to be able to reassign IP address)
 # manual_ip:
 #   static_ip: 192.168.18.80
#    gateway: 192.168.8.1
#    subnet: 255.255.255.0
#    dns1: 192.168.8.1